### ISSUE TITLE
Move raster Geopackage code created by Reinventing Geospatial

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-geopackage10#2]
Look at GeoPackage raster code and check/document how feasible it is to move it into testng.
https://github.com/GitHubRGI/swagd

**Comment by rjmartell** [comment]
The `VerifierTool` provides a GUI (based on JavaFX) for validating geopackages. The actual assertion checking is done by the various *Verifier classes in the `GeoPackage` module. The swagd developers implemented a custom testing framework for some reason.

**Comment by rjmartell** [comment]
The following conformance classes appear to be covered by the swagd/GeoPackage module:
- Core
- Tiles
- Schema
- Metadata

There are no checks for "Features" conformance.

**Comment by rjmartell** [comment]
See https://github.com/opengeospatial/ets-gpkg10
